import 'package:navojit_tech/features/investor/models/startup_deal.dart';

class MockInvestorData {
  MockInvestorData._();

  static const List<String> industries = [
    'FinTech',
    'HealthTech',
    'AI / ML',
    'SaaS',
    'CleanTech',
    'EdTech'
  ];

  static const List<String> stages = [
    'Pre-Seed',
    'Seed',
    'Series A',
    'Series B',
    'Growth'
  ];

  static final List<StartupDeal> startups = [
    StartupDeal(
      id: '1',
      name: 'NexusPay',
      tagline: 'Cross-border B2B payments on the blockchain.',
      industry: 'FinTech',
      stage: 'Series A',
      location: 'London, UK',
      askAmount: 3.5,
      valuation: 15.0,
      logoInitial: 'N',
      status: 'APPROVED',
      description: 'NexusPay is revolutionizing how enterprise businesses settle invoices internationally by utilizing stablecoins to bypass traditional banking rails, reducing fees by up to 80% and settlement times from days to seconds.',
      founder: const FounderProfile(
        name: 'Sarah Jenkins',
        title: 'CEO & Co-Founder',
        bio: 'Ex-Stripe and Revolut product lead with 10 years of experience in payment infrastructure.',
        initial: 'S',
      ),
    ),
    StartupDeal(
      id: '2',
      name: 'MediSync',
      tagline: 'AI-driven interoperability for legacy EHRs.',
      industry: 'HealthTech',
      stage: 'Seed',
      location: 'Boston, MA',
      askAmount: 1.2,
      valuation: 8.0,
      logoInitial: 'M',
      status: 'APPROVED',
      description: 'MediSync bridges the gap between disconnected hospital systems. Our proprietary NLP models extract unstructured patient data and structure it into FHIR standard records, enabling seamless care coordination.',
      founder: const FounderProfile(
        name: 'Dr. Rahul Mehta',
        title: 'Founder',
        bio: 'Practicing physician and self-taught engineer passionate about healthcare data liquidity.',
        initial: 'R',
      ),
    ),
    StartupDeal(
      id: '3',
      name: 'Aura',
      tagline: 'Generative UI for enterprise SaaS applications.',
      industry: 'AI / ML',
      stage: 'Pre-Seed',
      location: 'San Francisco, CA',
      askAmount: 0.5,
      valuation: 4.0,
      logoInitial: 'A',
      status: 'APPROVED',
      description: 'Aura allows product managers to generate functional frontend code directly from Figma designs and written specifications. We integrate deeply with React and Flutter ecosystems.',
      founder: const FounderProfile(
        name: 'David Chen',
        title: 'CTO & Co-Founder',
        bio: 'Former senior engineer at Google, focused on LLM applications for code generation.',
        initial: 'D',
      ),
    ),
    StartupDeal(
      id: '4',
      name: 'GreenGrid',
      tagline: 'Decentralized energy trading platform for microgrids.',
      industry: 'CleanTech',
      stage: 'Series A',
      location: 'Berlin, DE',
      askAmount: 5.0,
      valuation: 22.0,
      logoInitial: 'G',
      status: 'APPROVED',
      description: 'GreenGrid enables neighborhoods with solar infrastructure to trade excess energy peer-to-peer. Our smart contracts automatically balance supply and demand at hyper-local levels.',
      founder: const FounderProfile(
        name: 'Elena Rostova',
        title: 'CEO',
        bio: 'Serial entrepreneur in the renewable sector. Previously built and sold a solar analytics firm.',
        initial: 'E',
      ),
    ),
    StartupDeal(
      id: '5',
      name: 'Lumina Learning',
      tagline: 'VR-based immersive language immersion.',
      industry: 'EdTech',
      stage: 'Seed',
      location: 'Austin, TX',
      askAmount: 2.0,
      valuation: 10.0,
      logoInitial: 'L',
      status: 'APPROVED',
      description: 'Lumina Learning puts students in fully simulated foreign environments, utilizing spatial audio and conversational AI avatars to accelerate fluency 3x faster than traditional apps.',
      founder: const FounderProfile(
        name: 'Marcus Bell',
        title: 'Founder & CEO',
        bio: 'Polyglot and former Oculus VR designer.',
        initial: 'M',
      ),
    ),
    StartupDeal(
      id: '6',
      name: 'VaultEdge',
      tagline: 'Quantum-resistant encryption for cloud storage.',
      industry: 'SaaS',
      stage: 'Series B',
      location: 'Toronto, CA',
      askAmount: 12.0,
      valuation: 65.0,
      logoInitial: 'V',
      status: 'APPROVED',
      description: 'As quantum computing threatens traditional cryptography, VaultEdge provides a drop-in SDK for enterprise cloud providers to upgrade their encryption protocols seamlessly.',
      founder: const FounderProfile(
        name: 'Dr. Alan Turing',
        title: 'Chief Cryptographer',
        bio: 'PhD in post-quantum cryptography from MIT.',
        initial: 'A',
      ),
    ),
    StartupDeal(
      id: '7',
      name: 'FinFlow',
      tagline: 'Automated treasury management for startups.',
      industry: 'FinTech',
      stage: 'Seed',
      location: 'New York, NY',
      askAmount: 1.5,
      valuation: 7.5,
      logoInitial: 'F',
      status: 'APPROVED',
      description: 'FinFlow automates cash sweeps, yield generation, and runway forecasting for venture-backed startups, ensuring idle cash is always working securely.',
      founder: const FounderProfile(
        name: 'Chloe Kim',
        title: 'CEO',
        bio: 'Former investment banker who transitioned to startup CFO roles before founding FinFlow.',
        initial: 'C',
      ),
    ),
    StartupDeal(
      id: '8',
      name: 'SynthBio',
      tagline: 'Accelerating protein discovery with generative AI.',
      industry: 'HealthTech',
      stage: 'Series A',
      location: 'Cambridge, MA',
      askAmount: 8.0,
      valuation: 35.0,
      logoInitial: 'S',
      status: 'APPROVED',
      description: 'SynthBio uses transformer models to design novel proteins with specific binding affinities, drastically reducing the time required for early-stage drug discovery.',
      founder: const FounderProfile(
        name: 'James Watson',
        title: 'Co-Founder & CSO',
        bio: 'Bioinformatics researcher specializing in computational protein design.',
        initial: 'J',
      ),
    ),
  ];
}
